name: Auto PR to release

on:
  pull_request:
    # types:
    #   - closed
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  create-pr:
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'main'
    # && github.event.pull_request.merged == true
    steps:
        - name: Check out code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Create PR to release branch
          run: |
            ISSUEID=$(gh pr view ${{ github.event.pull_request.number }} --repo $OWNER/$REPO | grep -oP 'Fixes #\K\d+')
            echo "===========> $ISSUEID"
            ISSUE=$(gh issue view $ISSUEID --repo $OWNER/$REPO --json labels,assignees,milestone,title)
            echo "===========> $ISSUE"

            LABELS=$(echo $ISSUE | jq -r '.labels[] | select(.name) | .name' | jq -R -r -s -c 'split("\n")[:-1] | join(",")')
            ASSIGNEES=$(echo $ISSUE | jq -r '.assignees[] | select(.login) | .login' | jq -R -s -c 'split("\n")[:-1] | join(",")')
            MILESTONE=$(echo $ISSUE | jq -r '.milestone | select(.title) | .title')
            TITLE=$(echo $ISSUE | jq -r '.title')

            gh pr edit ${{ github.event.pull_request.number }} --repo $OWNER/$REPO --add-label "$LABELS" --add-assignee "$ASSIGNEES" --milestone "$MILESTONE"

            # git checkout -b bot/merge-to-release-$ISSUEID
            # git push origin bot/merge-to-release-$ISSUEID
            # gh pr create --base release --head bot/merge-to-release-$ISSUEID --title "Merge main to release" --body ""
            # gh pr create --base main --head feat/auto-release-pr-624  --title "The bug is fixed" --body "$x" --repo SoraEase/sora-prompt-zh --reviewer "cubxxw"
          continue-on-error: true
          env:
              GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
              GH_TOKEN: ${{ github.token }}
              ISSUE: ${{ github.event.issue.html_url }}
              OWNER: ${{ github.repository_owner }}
              REPO: ${{ github.event.repository.name }}
