name: Github Pull Request
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4


      - name: Generate Vertions
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1` | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
          echo $latest_tag > .github/version
        continue-on-error: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          commit-message: "cicd: bump League Patch"
          author: kubbot <3293172751ysy@gmail.com>
          committer: kubbot <3293172751ysy@gmail.com>
        #   signoff: false
        #   draft: false
          branch: "asf-auto-updates"
          assignees: cubxxw
          reviewers: cubxxw
          title: "[Auto PR 🤖] Bump League Patch auto PR"
          body: |
            I am a PR generated by robot automation.

            Review criteria:

            - [ ] Disenchanter can connect and issue actions

            Github Actions Status:

            [![Github Pull Request](https://github.com/SoraEase/sora-prompt-zh/actions/workflows/auto-pull-request.yml/badge.svg)](https://github.com/SoraEase/sora-prompt-zh/actions/workflows/aotu-pull-request.yml)
            
            This is an automated PR. 
            <sub>[workflow](https://github.com/SoraEase/sora-prompt-zh/blob/main/.github/workflows/pull-request.yml).</sub>
          labels: |
            kind/documentation
            enhancement
            report